-- 1. Setup Environment
-- Run this as SECURITYADMIN or ACCOUNTADMIN (or a role with CREATE DATABASE privileges)

USE ROLE SYSADMIN;

-- Create Database
CREATE DATABASE IF NOT EXISTS EDQM_DB;

-- Create Schema for Raw Data
CREATE SCHEMA IF NOT EXISTS EDQM_DB.RAW;

-- Create Warehouse for Compute
CREATE WAREHOUSE IF NOT EXISTS EDQM_WH
    WITH WAREHOUSE_SIZE = 'X-SMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE;

-- Context
USE WAREHOUSE EDQM_WH;
USE DATABASE EDQM_DB;
USE SCHEMA RAW;
